// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbjmcRbi9Q-Ed7SlcQm44nrlaDaUrVKRE',
    appId: '1:1067812698120:web:bc0fbd4527bdc6942bf9bd',
    messagingSenderId: '1067812698120',
    projectId: 'calcutortooo',
    authDomain: 'calcutortooo.firebaseapp.com',
    storageBucket: 'calcutortooo.appspot.com',
    measurementId: 'G-TK5T9D4PJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKGfZpUIVKU8w31e_3mgP7bb3SsGxHCU',
    appId: '1:1067812698120:android:c3563dce3fa2f9252bf9bd',
    messagingSenderId: '1067812698120',
    projectId: 'calcutortooo',
    storageBucket: 'calcutortooo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeBzomkfENB7KfaNtBNokQ9rEbri_xtLE',
    appId: '1:1067812698120:ios:14af5b30d0c901642bf9bd',
    messagingSenderId: '1067812698120',
    projectId: 'calcutortooo',
    storageBucket: 'calcutortooo.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeBzomkfENB7KfaNtBNokQ9rEbri_xtLE',
    appId: '1:1067812698120:ios:14af5b30d0c901642bf9bd',
    messagingSenderId: '1067812698120',
    projectId: 'calcutortooo',
    storageBucket: 'calcutortooo.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbjmcRbi9Q-Ed7SlcQm44nrlaDaUrVKRE',
    appId: '1:1067812698120:web:e86d5e75de4626ae2bf9bd',
    messagingSenderId: '1067812698120',
    projectId: 'calcutortooo',
    authDomain: 'calcutortooo.firebaseapp.com',
    storageBucket: 'calcutortooo.appspot.com',
    measurementId: 'G-9VDQYFTW7X',
  );

}